name: benchmark memcached

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: benchmark
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: |
          cd benchmarks
          bash run.sh setup_memcached.sh "-p 11211 -P memcache_text"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-2"
      - uses: actions/upload-artifact@v4
        with:
          name: profile.col
          path: benchmarks/profile.col
      - uses: actions/upload-artifact@v4
        with:
          name: profile_iostat.txt
          path: benchmarks/profile_iostat.txt
      - uses: actions/upload-artifact@v4
        with:
          name: profile_counters.csv
          path: benchmarks/profile_counters.csv
