name: benchmark redis

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: benchmark
    steps:
      - uses: actions/checkout@v4
      - name: Upload to S3
        run: |
          cd benchmarks/redis
          bash run.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-2"
